### ISSUE TITLE
design/layoutNav & homeFeed dot 스타일 수정

### ISSUE THREAD

**Issue by Yi-HyeonJu** [oz-collabo-project-team-03/oz_project_03_fe#114]
### 📃Description

> 사진에 묻히는 navbar css 수정
> homeFeed 게시물 css 수정 및 슬라이드 도트 보이게 css 수정

### 📌Todo

- [x] navbar css 수정
- [x] homeFeed 게시물 css 수정
- [x] 슬라이드 도트 css 수정

### 📝ETC

> 기타사항
