### ISSUE TITLE
design/프로필 수정 스타일 작업

### ISSUE THREAD

**Issue by Yi-HyeonJu** [oz-collabo-project-team-03/oz_project_03_fe#12]
### 📃Description

> 프로필 수정 스타일 작업

### 📌Todo

- [x] edit-profile 페이지 생성
- [x] my-page와 연결
- [x] edit-profile 페이지스타일 작업

### 📝ETC

> 프로필 이미지를 로그인한 타입별로 학생과 선생님 나누어 보여주기
