### ISSUE TITLE
fix/애니메이션 에러 수정 및 보완

### ISSUE THREAD

**Issue by deswaq1220** [oz-collabo-project-team-03/oz_project_03_fe#157]
### 📃Description

> 애니메이션 에러 수정 및 보완

### 📌Todo

- [x] 역할별 선택 버튼 css 호버시 따로노는 현상
- [x] 선생님 선택 모달 커스텀 스크롤바 적용
- [x] 댓글 스켈레톤 ui 

### 📝ETC

> 기타사항
