### ISSUE TITLE
fix/ 새로고침 시 /login으로 이동하는 오류

### ISSUE THREAD

**Issue by deswaq1220** [oz-collabo-project-team-03/oz_project_03_fe#166]
### 📃Description

>  채팅페이지에서 새로고침시 /login으로 이동하는 오류, 롤이 다른 유저 계정을 각각 로그인 시 액세스토큰이 한번 더 들어오는 에러

### 📌Todo

- [x] 채팅페이지에서 새로고침시 /login으로 이동하는 오류
- [x] 롤이 다른 유저 계정을 각각 로그인 시 액세스토큰이 한번 더 들어오는 에러
- [x] 선생님 로그인시 선생님 선택모달 뜨는 에러

### 📝ETC

> 기타사항
