### ISSUE TITLE
Feat: 좋아요 기능 서버와 연동하여 상태 및 카운트 관리

### ISSUE THREAD

**Issue by doin-N** [oz-collabo-project-team-03/oz_project_03_fe#172]
### 📃Description

>  좋아요 상태가 새로고침 시 사라지는 문제와, 좋아요 상태 업데이트 후 UI에 미반영되는 문제를 수정
또한, 게시물별로 고유한 좋아요 카운트를 제대로 표시할 수 있도록 개선

### 📌Todo

- [x] 좋아요 상태와 카운트를 서버 API와 연동
- [x] 좋아요 상태가 새로고침 시 사라지는 문제 수정
- [x] 좋아요 상태 업데이트 후 UI에 미반영되는 문제 수정
- [x] 게시물별 고유 좋아요 카운트 표시 기능 추가

### 📝ETC

> 기타사항
