### ISSUE TITLE
design/랜딩 페이지 스타일 작업

### ISSUE THREAD

**Issue by Yi-HyeonJu** [oz-collabo-project-team-03/oz_project_03_fe#18]
### 📃Description

> 랜딩페이지 제작

### 📌Todo

- [x] 1차 버블 부분 제작
- [x] 2차 아이폰 모형 부분 제작
- [x] 1차, 2차를 슬라이드로 연결하기

### 📝ETC

> 기타사항
