### ISSUE TITLE
design/포스팅 페이지 스타일 작업

### ISSUE THREAD

**Issue by doin-N** [oz-collabo-project-team-03/oz_project_03_fe#51]
### 📃Description

>  포스팅 페이지 스타일 작업

### 📌Todo

- [x] imageUpload 컴포넌트 생성
- [x] textEditor 컴포넌트 생성
- [x] 포스팅 페이지 스타일 작업

### 📝ETC

>
