### ISSUE TITLE
design/선생님 메인페이지 스타일 작업

### ISSUE THREAD

**Issue by doin-N** [oz-collabo-project-team-03/oz_project_03_fe#56]
### 📃Description

> 선생님 메인 페인지 (관리하는 학생 리스트) 스타일 작업

### 📌Todo

- [x] managedList 컴포넌트 생성
- [x] teacherInfo 컴포넌트 생성
- [x] 관리하는 학생 리스트 (선생님 메인 페인지) 스타일 작업

### 📝ETC

> 기타사항
